### ISSUE TITLE
data shape error

### ISSUE THREAD

**Issue by alphamol-basel** [schallerdavid/pyrod#12]
Hello developers:
I am trying to use pyrod with trajectory_analysis.cfg file.

The trajectory_analysis.cfg file fellows:
[directory]
directory:

[trajectory analysis parameters]
center:        48,  40,  35
edge lengths: 35, 35, 35
topology: /data/shiyu/tmp_pyrod/protein_UNK_prod.gro
trajectories: /data/shiyu/tmp_pyrod/protein_UNK_prod.xtc
first frame: 100
last frame: 200
step size: 1
metal names:
map formats: cns, xplor, kont
number of processes: 1
dmifs only: false

The error information appears on my screen:
Starting trajectory analysis.
Initializing grid.
Analyzing 101 frames from 1 trajectory.
Process Process-2:
Traceback (most recent call last):
  File "/soft/anaconda3/2022.05/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/soft/anaconda3/2022.05/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/soft/AIDD/pyrod/pyrod_lib/trajectory.py", line 68, in trajectory_analysis
    hd_atomids, hd_types, hd_hydrogen_atomid_lists = hd_selection(main_atoms)
  File "/soft/AIDD/pyrod/pyrod_lib/trajectory_helper.py", line 85, in hd_selection
    return np.array(atomids), np.array(types), np.array(hydrogen_atomid_lists)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (354,) + inhomogeneous part.
Processing results.
Traceback (most recent call last):
  File "/soft/AIDD/pyrod/pyrod.py", line 130, in <module>
    dmif, partners = post_processing(results_list, total_number_of_frames)
  File "/soft/AIDD/pyrod/pyrod_lib/grid.py", line 85, in post_processing

I don't know how to make it works.

**Comment by schallerdavid** [comment]
Hello,

can you try to downgrade numpy to version 1.21.1? This fixed numpy issues before [issue](https://github.com/wolberlab/pyrod/issues/11#issuecomment-1689860959).

Best regards,
David

**Comment by alphamol-basel** [comment]
Thank you! It is solved!
