### ISSUE TITLE
errot

### ISSUE THREAD

**Issue by boyuezhong** [schallerdavid/pyrod#7]
FileNotFoundError: [Errno 2] No such file or directory: '/hdd1/software/pyrod/pyrod/centroid/frames_0.csv'

Traceback (most recent call last):
  File "pyrod.py", line 240, in <module>
    ensemble_to_centroid(topology, trajectories, output_name, directory, debugging)
  File "/hdd1/software/pyrod/pyrod_lib/trajectory.py", line 578, in ensemble_to_centroid
    with open('{}/frames_{}.csv'.format(output_directory, x), 'r') as csv:
FileNotFoundError: [Errno 2] No such file or directory: '/hdd1/software/pyrod/pyrod/centroid/frames_0.csv'

**Comment by schallerdavid** [comment]
@boyuezhong sorry for responding so late, is this still an issue or did you resolve the problem already?
Best regards,
David
